[workspace]
members = [
    "crates/nezha-agent",
    "crates/nezha-core",
    "crates/nezha-dashboard",
    "crates/nezha-proto",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "Apache-2.0"
repository = "https://github.com/nezha-rs/nezha-rs"
rust-version = "1.95"
version = "0.1.0"

[workspace.dependencies]
anyhow = "1.0.100"
async-stream = "0.3.6"
axum = { version = "0.8.9", features = ["ws"] }
bcrypt = "0.19.1"
chrono = { version = "0.4.42", features = ["serde"] }
clap = { version = "4.6.0", features = ["derive", "env"] }
cron = "0.16.0"
futures-util = "0.3.31"
hickory-resolver = { version = "0.24.4", default-features = false, features = ["tokio-runtime"] }
jsonwebtoken = { version = "10.4.0", features = ["rust_crypto"] }
libc = "0.2.178"
maxminddb = "0.28.1"
prost = "0.14.1"
protoc-bin-vendored = "3.2.0"
reqwest = { version = "0.12.28", default-features = false, features = ["charset", "http2", "rustls-tls"] }
rusqlite = { version = "0.39.0", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9.34"
sysinfo = "0.39.2"
tokio = { version = "1.52.3", features = ["fs", "io-util", "macros", "net", "process", "rt-multi-thread", "signal", "sync", "time"] }
tokio-rustls = "0.26.4"
tokio-stream = "0.1.17"
tonic = { version = "0.14.6", features = ["tls-native-roots"] }
tonic-prost = "0.14.6"
tonic-prost-build = "0.14.6"
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "fmt"] }
uuid = { version = "1.19.0", features = ["v4", "serde"] }
x509-parser = "0.18.1"
